### PR TITLE
Move from Travis CI to GitHub Actions CI 

### PR DESCRIPTION
**Pull request by DilumAluthge**
cc: @ablaom @tlienart

### CODE REVIEW

**Comment by DilumAluthge** [comment]
@ablaom @tlienart This is ready to merge.

**Comment by ablaom** [comment]
@DilumAluthge Couldn't figure out why ci is not being triggered here. Any idea?

**Comment by DilumAluthge** [comment]
First, double check that Actions are enabled on this repo. 

https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/disabling-or-limiting-github-actions-for-a-repository

If they are, then usually merged the PR into master will enable the workflow.

**Comment by ablaom** [comment]
Will do. 

Unrelated note: Locally this PR is failing because of a LossFunctions bug with workaround in https://github.com/alan-turing-institute/MLJBase.jl/pull/466 .

**Pull request merged**
